// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"github.com/drakejin/crawler/internal/storage/db/ent/pageinfo"
	"github.com/drakejin/crawler/internal/storage/db/ent/pagelink"
	"github.com/drakejin/crawler/internal/storage/db/ent/predicate"

	"entgo.io/ent"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypePageInfo = "PageInfo"
	TypePageLink = "PageLink"
)

// PageInfoMutation represents an operation that mutates the PageInfo nodes in the graph.
type PageInfoMutation struct {
	config
	op                  Op
	typ                 string
	id                  *int64
	domain              *string
	port                *string
	is_https            *bool
	indexed_url         *string
	_path               *string
	querystring         *string
	url                 *string
	count_referred      *int64
	addcount_referred   *int64
	status              *pageinfo.Status
	created_at          *time.Time
	created_by          *string
	updated_at          *time.Time
	updated_by          *string
	title               *string
	description         *string
	keywords            *string
	content_language    *string
	twitter_card        *string
	twitter_url         *string
	twitter_title       *string
	twitter_description *string
	twitter_image       *string
	og_site_name        *string
	og_locale           *string
	og_title            *string
	og_description      *string
	og_type             *string
	og_url              *string
	og_image            *string
	og_image_type       *string
	og_image_url        *string
	og_image_secure_url *string
	og_image_width      *string
	og_image_height     *string
	og_video            *string
	og_video_type       *string
	og_video_url        *string
	og_video_secure_url *string
	og_video_width      *string
	og_video_height     *string
	clearedFields       map[string]struct{}
	done                bool
	oldValue            func(context.Context) (*PageInfo, error)
	predicates          []predicate.PageInfo
}

var _ ent.Mutation = (*PageInfoMutation)(nil)

// pageinfoOption allows management of the mutation configuration using functional options.
type pageinfoOption func(*PageInfoMutation)

// newPageInfoMutation creates new mutation for the PageInfo entity.
func newPageInfoMutation(c config, op Op, opts ...pageinfoOption) *PageInfoMutation {
	m := &PageInfoMutation{
		config:        c,
		op:            op,
		typ:           TypePageInfo,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withPageInfoID sets the ID field of the mutation.
func withPageInfoID(id int64) pageinfoOption {
	return func(m *PageInfoMutation) {
		var (
			err   error
			once  sync.Once
			value *PageInfo
		)
		m.oldValue = func(ctx context.Context) (*PageInfo, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().PageInfo.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withPageInfo sets the old PageInfo of the mutation.
func withPageInfo(node *PageInfo) pageinfoOption {
	return func(m *PageInfoMutation) {
		m.oldValue = func(context.Context) (*PageInfo, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m PageInfoMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m PageInfoMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of PageInfo entities.
func (m *PageInfoMutation) SetID(id int64) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *PageInfoMutation) ID() (id int64, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *PageInfoMutation) IDs(ctx context.Context) ([]int64, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int64{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().PageInfo.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetDomain sets the "domain" field.
func (m *PageInfoMutation) SetDomain(s string) {
	m.domain = &s
}

// Domain returns the value of the "domain" field in the mutation.
func (m *PageInfoMutation) Domain() (r string, exists bool) {
	v := m.domain
	if v == nil {
		return
	}
	return *v, true
}

// OldDomain returns the old "domain" field's value of the PageInfo entity.
// If the PageInfo object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PageInfoMutation) OldDomain(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDomain is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDomain requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDomain: %w", err)
	}
	return oldValue.Domain, nil
}

// ResetDomain resets all changes to the "domain" field.
func (m *PageInfoMutation) ResetDomain() {
	m.domain = nil
}

// SetPort sets the "port" field.
func (m *PageInfoMutation) SetPort(s string) {
	m.port = &s
}

// Port returns the value of the "port" field in the mutation.
func (m *PageInfoMutation) Port() (r string, exists bool) {
	v := m.port
	if v == nil {
		return
	}
	return *v, true
}

// OldPort returns the old "port" field's value of the PageInfo entity.
// If the PageInfo object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PageInfoMutation) OldPort(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPort is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPort requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPort: %w", err)
	}
	return oldValue.Port, nil
}

// ResetPort resets all changes to the "port" field.
func (m *PageInfoMutation) ResetPort() {
	m.port = nil
}

// SetIsHTTPS sets the "is_https" field.
func (m *PageInfoMutation) SetIsHTTPS(b bool) {
	m.is_https = &b
}

// IsHTTPS returns the value of the "is_https" field in the mutation.
func (m *PageInfoMutation) IsHTTPS() (r bool, exists bool) {
	v := m.is_https
	if v == nil {
		return
	}
	return *v, true
}

// OldIsHTTPS returns the old "is_https" field's value of the PageInfo entity.
// If the PageInfo object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PageInfoMutation) OldIsHTTPS(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIsHTTPS is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIsHTTPS requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIsHTTPS: %w", err)
	}
	return oldValue.IsHTTPS, nil
}

// ResetIsHTTPS resets all changes to the "is_https" field.
func (m *PageInfoMutation) ResetIsHTTPS() {
	m.is_https = nil
}

// SetIndexedURL sets the "indexed_url" field.
func (m *PageInfoMutation) SetIndexedURL(s string) {
	m.indexed_url = &s
}

// IndexedURL returns the value of the "indexed_url" field in the mutation.
func (m *PageInfoMutation) IndexedURL() (r string, exists bool) {
	v := m.indexed_url
	if v == nil {
		return
	}
	return *v, true
}

// OldIndexedURL returns the old "indexed_url" field's value of the PageInfo entity.
// If the PageInfo object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PageInfoMutation) OldIndexedURL(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIndexedURL is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIndexedURL requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIndexedURL: %w", err)
	}
	return oldValue.IndexedURL, nil
}

// ResetIndexedURL resets all changes to the "indexed_url" field.
func (m *PageInfoMutation) ResetIndexedURL() {
	m.indexed_url = nil
}

// SetPath sets the "path" field.
func (m *PageInfoMutation) SetPath(s string) {
	m._path = &s
}

// Path returns the value of the "path" field in the mutation.
func (m *PageInfoMutation) Path() (r string, exists bool) {
	v := m._path
	if v == nil {
		return
	}
	return *v, true
}

// OldPath returns the old "path" field's value of the PageInfo entity.
// If the PageInfo object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PageInfoMutation) OldPath(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPath is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPath requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPath: %w", err)
	}
	return oldValue.Path, nil
}

// ResetPath resets all changes to the "path" field.
func (m *PageInfoMutation) ResetPath() {
	m._path = nil
}

// SetQuerystring sets the "querystring" field.
func (m *PageInfoMutation) SetQuerystring(s string) {
	m.querystring = &s
}

// Querystring returns the value of the "querystring" field in the mutation.
func (m *PageInfoMutation) Querystring() (r string, exists bool) {
	v := m.querystring
	if v == nil {
		return
	}
	return *v, true
}

// OldQuerystring returns the old "querystring" field's value of the PageInfo entity.
// If the PageInfo object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PageInfoMutation) OldQuerystring(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldQuerystring is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldQuerystring requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldQuerystring: %w", err)
	}
	return oldValue.Querystring, nil
}

// ResetQuerystring resets all changes to the "querystring" field.
func (m *PageInfoMutation) ResetQuerystring() {
	m.querystring = nil
}

// SetURL sets the "url" field.
func (m *PageInfoMutation) SetURL(s string) {
	m.url = &s
}

// URL returns the value of the "url" field in the mutation.
func (m *PageInfoMutation) URL() (r string, exists bool) {
	v := m.url
	if v == nil {
		return
	}
	return *v, true
}

// OldURL returns the old "url" field's value of the PageInfo entity.
// If the PageInfo object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PageInfoMutation) OldURL(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldURL is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldURL requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldURL: %w", err)
	}
	return oldValue.URL, nil
}

// ResetURL resets all changes to the "url" field.
func (m *PageInfoMutation) ResetURL() {
	m.url = nil
}

// SetCountReferred sets the "count_referred" field.
func (m *PageInfoMutation) SetCountReferred(i int64) {
	m.count_referred = &i
	m.addcount_referred = nil
}

// CountReferred returns the value of the "count_referred" field in the mutation.
func (m *PageInfoMutation) CountReferred() (r int64, exists bool) {
	v := m.count_referred
	if v == nil {
		return
	}
	return *v, true
}

// OldCountReferred returns the old "count_referred" field's value of the PageInfo entity.
// If the PageInfo object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PageInfoMutation) OldCountReferred(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCountReferred is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCountReferred requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCountReferred: %w", err)
	}
	return oldValue.CountReferred, nil
}

// AddCountReferred adds i to the "count_referred" field.
func (m *PageInfoMutation) AddCountReferred(i int64) {
	if m.addcount_referred != nil {
		*m.addcount_referred += i
	} else {
		m.addcount_referred = &i
	}
}

// AddedCountReferred returns the value that was added to the "count_referred" field in this mutation.
func (m *PageInfoMutation) AddedCountReferred() (r int64, exists bool) {
	v := m.addcount_referred
	if v == nil {
		return
	}
	return *v, true
}

// ResetCountReferred resets all changes to the "count_referred" field.
func (m *PageInfoMutation) ResetCountReferred() {
	m.count_referred = nil
	m.addcount_referred = nil
}

// SetStatus sets the "status" field.
func (m *PageInfoMutation) SetStatus(pa pageinfo.Status) {
	m.status = &pa
}

// Status returns the value of the "status" field in the mutation.
func (m *PageInfoMutation) Status() (r pageinfo.Status, exists bool) {
	v := m.status
	if v == nil {
		return
	}
	return *v, true
}

// OldStatus returns the old "status" field's value of the PageInfo entity.
// If the PageInfo object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PageInfoMutation) OldStatus(ctx context.Context) (v pageinfo.Status, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStatus is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStatus requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStatus: %w", err)
	}
	return oldValue.Status, nil
}

// ResetStatus resets all changes to the "status" field.
func (m *PageInfoMutation) ResetStatus() {
	m.status = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *PageInfoMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *PageInfoMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the PageInfo entity.
// If the PageInfo object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PageInfoMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *PageInfoMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetCreatedBy sets the "created_by" field.
func (m *PageInfoMutation) SetCreatedBy(s string) {
	m.created_by = &s
}

// CreatedBy returns the value of the "created_by" field in the mutation.
func (m *PageInfoMutation) CreatedBy() (r string, exists bool) {
	v := m.created_by
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedBy returns the old "created_by" field's value of the PageInfo entity.
// If the PageInfo object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PageInfoMutation) OldCreatedBy(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedBy is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedBy requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedBy: %w", err)
	}
	return oldValue.CreatedBy, nil
}

// ResetCreatedBy resets all changes to the "created_by" field.
func (m *PageInfoMutation) ResetCreatedBy() {
	m.created_by = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *PageInfoMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *PageInfoMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the PageInfo entity.
// If the PageInfo object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PageInfoMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *PageInfoMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// SetUpdatedBy sets the "updated_by" field.
func (m *PageInfoMutation) SetUpdatedBy(s string) {
	m.updated_by = &s
}

// UpdatedBy returns the value of the "updated_by" field in the mutation.
func (m *PageInfoMutation) UpdatedBy() (r string, exists bool) {
	v := m.updated_by
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedBy returns the old "updated_by" field's value of the PageInfo entity.
// If the PageInfo object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PageInfoMutation) OldUpdatedBy(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedBy is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedBy requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedBy: %w", err)
	}
	return oldValue.UpdatedBy, nil
}

// ResetUpdatedBy resets all changes to the "updated_by" field.
func (m *PageInfoMutation) ResetUpdatedBy() {
	m.updated_by = nil
}

// SetTitle sets the "title" field.
func (m *PageInfoMutation) SetTitle(s string) {
	m.title = &s
}

// Title returns the value of the "title" field in the mutation.
func (m *PageInfoMutation) Title() (r string, exists bool) {
	v := m.title
	if v == nil {
		return
	}
	return *v, true
}

// OldTitle returns the old "title" field's value of the PageInfo entity.
// If the PageInfo object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PageInfoMutation) OldTitle(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTitle is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTitle requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTitle: %w", err)
	}
	return oldValue.Title, nil
}

// ResetTitle resets all changes to the "title" field.
func (m *PageInfoMutation) ResetTitle() {
	m.title = nil
}

// SetDescription sets the "description" field.
func (m *PageInfoMutation) SetDescription(s string) {
	m.description = &s
}

// Description returns the value of the "description" field in the mutation.
func (m *PageInfoMutation) Description() (r string, exists bool) {
	v := m.description
	if v == nil {
		return
	}
	return *v, true
}

// OldDescription returns the old "description" field's value of the PageInfo entity.
// If the PageInfo object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PageInfoMutation) OldDescription(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDescription is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDescription requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDescription: %w", err)
	}
	return oldValue.Description, nil
}

// ResetDescription resets all changes to the "description" field.
func (m *PageInfoMutation) ResetDescription() {
	m.description = nil
}

// SetKeywords sets the "keywords" field.
func (m *PageInfoMutation) SetKeywords(s string) {
	m.keywords = &s
}

// Keywords returns the value of the "keywords" field in the mutation.
func (m *PageInfoMutation) Keywords() (r string, exists bool) {
	v := m.keywords
	if v == nil {
		return
	}
	return *v, true
}

// OldKeywords returns the old "keywords" field's value of the PageInfo entity.
// If the PageInfo object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PageInfoMutation) OldKeywords(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldKeywords is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldKeywords requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldKeywords: %w", err)
	}
	return oldValue.Keywords, nil
}

// ResetKeywords resets all changes to the "keywords" field.
func (m *PageInfoMutation) ResetKeywords() {
	m.keywords = nil
}

// SetContentLanguage sets the "content_language" field.
func (m *PageInfoMutation) SetContentLanguage(s string) {
	m.content_language = &s
}

// ContentLanguage returns the value of the "content_language" field in the mutation.
func (m *PageInfoMutation) ContentLanguage() (r string, exists bool) {
	v := m.content_language
	if v == nil {
		return
	}
	return *v, true
}

// OldContentLanguage returns the old "content_language" field's value of the PageInfo entity.
// If the PageInfo object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PageInfoMutation) OldContentLanguage(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldContentLanguage is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldContentLanguage requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldContentLanguage: %w", err)
	}
	return oldValue.ContentLanguage, nil
}

// ResetContentLanguage resets all changes to the "content_language" field.
func (m *PageInfoMutation) ResetContentLanguage() {
	m.content_language = nil
}

// SetTwitterCard sets the "twitter_card" field.
func (m *PageInfoMutation) SetTwitterCard(s string) {
	m.twitter_card = &s
}

// TwitterCard returns the value of the "twitter_card" field in the mutation.
func (m *PageInfoMutation) TwitterCard() (r string, exists bool) {
	v := m.twitter_card
	if v == nil {
		return
	}
	return *v, true
}

// OldTwitterCard returns the old "twitter_card" field's value of the PageInfo entity.
// If the PageInfo object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PageInfoMutation) OldTwitterCard(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTwitterCard is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTwitterCard requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTwitterCard: %w", err)
	}
	return oldValue.TwitterCard, nil
}

// ResetTwitterCard resets all changes to the "twitter_card" field.
func (m *PageInfoMutation) ResetTwitterCard() {
	m.twitter_card = nil
}

// SetTwitterURL sets the "twitter_url" field.
func (m *PageInfoMutation) SetTwitterURL(s string) {
	m.twitter_url = &s
}

// TwitterURL returns the value of the "twitter_url" field in the mutation.
func (m *PageInfoMutation) TwitterURL() (r string, exists bool) {
	v := m.twitter_url
	if v == nil {
		return
	}
	return *v, true
}

// OldTwitterURL returns the old "twitter_url" field's value of the PageInfo entity.
// If the PageInfo object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PageInfoMutation) OldTwitterURL(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTwitterURL is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTwitterURL requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTwitterURL: %w", err)
	}
	return oldValue.TwitterURL, nil
}

// ResetTwitterURL resets all changes to the "twitter_url" field.
func (m *PageInfoMutation) ResetTwitterURL() {
	m.twitter_url = nil
}

// SetTwitterTitle sets the "twitter_title" field.
func (m *PageInfoMutation) SetTwitterTitle(s string) {
	m.twitter_title = &s
}

// TwitterTitle returns the value of the "twitter_title" field in the mutation.
func (m *PageInfoMutation) TwitterTitle() (r string, exists bool) {
	v := m.twitter_title
	if v == nil {
		return
	}
	return *v, true
}

// OldTwitterTitle returns the old "twitter_title" field's value of the PageInfo entity.
// If the PageInfo object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PageInfoMutation) OldTwitterTitle(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTwitterTitle is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTwitterTitle requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTwitterTitle: %w", err)
	}
	return oldValue.TwitterTitle, nil
}

// ResetTwitterTitle resets all changes to the "twitter_title" field.
func (m *PageInfoMutation) ResetTwitterTitle() {
	m.twitter_title = nil
}

// SetTwitterDescription sets the "twitter_description" field.
func (m *PageInfoMutation) SetTwitterDescription(s string) {
	m.twitter_description = &s
}

// TwitterDescription returns the value of the "twitter_description" field in the mutation.
func (m *PageInfoMutation) TwitterDescription() (r string, exists bool) {
	v := m.twitter_description
	if v == nil {
		return
	}
	return *v, true
}

// OldTwitterDescription returns the old "twitter_description" field's value of the PageInfo entity.
// If the PageInfo object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PageInfoMutation) OldTwitterDescription(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTwitterDescription is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTwitterDescription requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTwitterDescription: %w", err)
	}
	return oldValue.TwitterDescription, nil
}

// ResetTwitterDescription resets all changes to the "twitter_description" field.
func (m *PageInfoMutation) ResetTwitterDescription() {
	m.twitter_description = nil
}

// SetTwitterImage sets the "twitter_image" field.
func (m *PageInfoMutation) SetTwitterImage(s string) {
	m.twitter_image = &s
}

// TwitterImage returns the value of the "twitter_image" field in the mutation.
func (m *PageInfoMutation) TwitterImage() (r string, exists bool) {
	v := m.twitter_image
	if v == nil {
		return
	}
	return *v, true
}

// OldTwitterImage returns the old "twitter_image" field's value of the PageInfo entity.
// If the PageInfo object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PageInfoMutation) OldTwitterImage(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTwitterImage is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTwitterImage requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTwitterImage: %w", err)
	}
	return oldValue.TwitterImage, nil
}

// ResetTwitterImage resets all changes to the "twitter_image" field.
func (m *PageInfoMutation) ResetTwitterImage() {
	m.twitter_image = nil
}

// SetOgSiteName sets the "og_site_name" field.
func (m *PageInfoMutation) SetOgSiteName(s string) {
	m.og_site_name = &s
}

// OgSiteName returns the value of the "og_site_name" field in the mutation.
func (m *PageInfoMutation) OgSiteName() (r string, exists bool) {
	v := m.og_site_name
	if v == nil {
		return
	}
	return *v, true
}

// OldOgSiteName returns the old "og_site_name" field's value of the PageInfo entity.
// If the PageInfo object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PageInfoMutation) OldOgSiteName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOgSiteName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOgSiteName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOgSiteName: %w", err)
	}
	return oldValue.OgSiteName, nil
}

// ResetOgSiteName resets all changes to the "og_site_name" field.
func (m *PageInfoMutation) ResetOgSiteName() {
	m.og_site_name = nil
}

// SetOgLocale sets the "og_locale" field.
func (m *PageInfoMutation) SetOgLocale(s string) {
	m.og_locale = &s
}

// OgLocale returns the value of the "og_locale" field in the mutation.
func (m *PageInfoMutation) OgLocale() (r string, exists bool) {
	v := m.og_locale
	if v == nil {
		return
	}
	return *v, true
}

// OldOgLocale returns the old "og_locale" field's value of the PageInfo entity.
// If the PageInfo object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PageInfoMutation) OldOgLocale(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOgLocale is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOgLocale requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOgLocale: %w", err)
	}
	return oldValue.OgLocale, nil
}

// ResetOgLocale resets all changes to the "og_locale" field.
func (m *PageInfoMutation) ResetOgLocale() {
	m.og_locale = nil
}

// SetOgTitle sets the "og_title" field.
func (m *PageInfoMutation) SetOgTitle(s string) {
	m.og_title = &s
}

// OgTitle returns the value of the "og_title" field in the mutation.
func (m *PageInfoMutation) OgTitle() (r string, exists bool) {
	v := m.og_title
	if v == nil {
		return
	}
	return *v, true
}

// OldOgTitle returns the old "og_title" field's value of the PageInfo entity.
// If the PageInfo object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PageInfoMutation) OldOgTitle(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOgTitle is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOgTitle requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOgTitle: %w", err)
	}
	return oldValue.OgTitle, nil
}

// ResetOgTitle resets all changes to the "og_title" field.
func (m *PageInfoMutation) ResetOgTitle() {
	m.og_title = nil
}

// SetOgDescription sets the "og_description" field.
func (m *PageInfoMutation) SetOgDescription(s string) {
	m.og_description = &s
}

// OgDescription returns the value of the "og_description" field in the mutation.
func (m *PageInfoMutation) OgDescription() (r string, exists bool) {
	v := m.og_description
	if v == nil {
		return
	}
	return *v, true
}

// OldOgDescription returns the old "og_description" field's value of the PageInfo entity.
// If the PageInfo object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PageInfoMutation) OldOgDescription(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOgDescription is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOgDescription requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOgDescription: %w", err)
	}
	return oldValue.OgDescription, nil
}

// ResetOgDescription resets all changes to the "og_description" field.
func (m *PageInfoMutation) ResetOgDescription() {
	m.og_description = nil
}

// SetOgType sets the "og_type" field.
func (m *PageInfoMutation) SetOgType(s string) {
	m.og_type = &s
}

// OgType returns the value of the "og_type" field in the mutation.
func (m *PageInfoMutation) OgType() (r string, exists bool) {
	v := m.og_type
	if v == nil {
		return
	}
	return *v, true
}

// OldOgType returns the old "og_type" field's value of the PageInfo entity.
// If the PageInfo object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PageInfoMutation) OldOgType(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOgType is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOgType requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOgType: %w", err)
	}
	return oldValue.OgType, nil
}

// ResetOgType resets all changes to the "og_type" field.
func (m *PageInfoMutation) ResetOgType() {
	m.og_type = nil
}

// SetOgURL sets the "og_url" field.
func (m *PageInfoMutation) SetOgURL(s string) {
	m.og_url = &s
}

// OgURL returns the value of the "og_url" field in the mutation.
func (m *PageInfoMutation) OgURL() (r string, exists bool) {
	v := m.og_url
	if v == nil {
		return
	}
	return *v, true
}

// OldOgURL returns the old "og_url" field's value of the PageInfo entity.
// If the PageInfo object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PageInfoMutation) OldOgURL(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOgURL is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOgURL requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOgURL: %w", err)
	}
	return oldValue.OgURL, nil
}

// ResetOgURL resets all changes to the "og_url" field.
func (m *PageInfoMutation) ResetOgURL() {
	m.og_url = nil
}

// SetOgImage sets the "og_image" field.
func (m *PageInfoMutation) SetOgImage(s string) {
	m.og_image = &s
}

// OgImage returns the value of the "og_image" field in the mutation.
func (m *PageInfoMutation) OgImage() (r string, exists bool) {
	v := m.og_image
	if v == nil {
		return
	}
	return *v, true
}

// OldOgImage returns the old "og_image" field's value of the PageInfo entity.
// If the PageInfo object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PageInfoMutation) OldOgImage(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOgImage is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOgImage requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOgImage: %w", err)
	}
	return oldValue.OgImage, nil
}

// ResetOgImage resets all changes to the "og_image" field.
func (m *PageInfoMutation) ResetOgImage() {
	m.og_image = nil
}

// SetOgImageType sets the "og_image_type" field.
func (m *PageInfoMutation) SetOgImageType(s string) {
	m.og_image_type = &s
}

// OgImageType returns the value of the "og_image_type" field in the mutation.
func (m *PageInfoMutation) OgImageType() (r string, exists bool) {
	v := m.og_image_type
	if v == nil {
		return
	}
	return *v, true
}

// OldOgImageType returns the old "og_image_type" field's value of the PageInfo entity.
// If the PageInfo object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PageInfoMutation) OldOgImageType(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOgImageType is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOgImageType requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOgImageType: %w", err)
	}
	return oldValue.OgImageType, nil
}

// ResetOgImageType resets all changes to the "og_image_type" field.
func (m *PageInfoMutation) ResetOgImageType() {
	m.og_image_type = nil
}

// SetOgImageURL sets the "og_image_url" field.
func (m *PageInfoMutation) SetOgImageURL(s string) {
	m.og_image_url = &s
}

// OgImageURL returns the value of the "og_image_url" field in the mutation.
func (m *PageInfoMutation) OgImageURL() (r string, exists bool) {
	v := m.og_image_url
	if v == nil {
		return
	}
	return *v, true
}

// OldOgImageURL returns the old "og_image_url" field's value of the PageInfo entity.
// If the PageInfo object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PageInfoMutation) OldOgImageURL(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOgImageURL is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOgImageURL requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOgImageURL: %w", err)
	}
	return oldValue.OgImageURL, nil
}

// ResetOgImageURL resets all changes to the "og_image_url" field.
func (m *PageInfoMutation) ResetOgImageURL() {
	m.og_image_url = nil
}

// SetOgImageSecureURL sets the "og_image_secure_url" field.
func (m *PageInfoMutation) SetOgImageSecureURL(s string) {
	m.og_image_secure_url = &s
}

// OgImageSecureURL returns the value of the "og_image_secure_url" field in the mutation.
func (m *PageInfoMutation) OgImageSecureURL() (r string, exists bool) {
	v := m.og_image_secure_url
	if v == nil {
		return
	}
	return *v, true
}

// OldOgImageSecureURL returns the old "og_image_secure_url" field's value of the PageInfo entity.
// If the PageInfo object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PageInfoMutation) OldOgImageSecureURL(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOgImageSecureURL is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOgImageSecureURL requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOgImageSecureURL: %w", err)
	}
	return oldValue.OgImageSecureURL, nil
}

// ResetOgImageSecureURL resets all changes to the "og_image_secure_url" field.
func (m *PageInfoMutation) ResetOgImageSecureURL() {
	m.og_image_secure_url = nil
}

// SetOgImageWidth sets the "og_image_width" field.
func (m *PageInfoMutation) SetOgImageWidth(s string) {
	m.og_image_width = &s
}

// OgImageWidth returns the value of the "og_image_width" field in the mutation.
func (m *PageInfoMutation) OgImageWidth() (r string, exists bool) {
	v := m.og_image_width
	if v == nil {
		return
	}
	return *v, true
}

// OldOgImageWidth returns the old "og_image_width" field's value of the PageInfo entity.
// If the PageInfo object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PageInfoMutation) OldOgImageWidth(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOgImageWidth is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOgImageWidth requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOgImageWidth: %w", err)
	}
	return oldValue.OgImageWidth, nil
}

// ResetOgImageWidth resets all changes to the "og_image_width" field.
func (m *PageInfoMutation) ResetOgImageWidth() {
	m.og_image_width = nil
}

// SetOgImageHeight sets the "og_image_height" field.
func (m *PageInfoMutation) SetOgImageHeight(s string) {
	m.og_image_height = &s
}

// OgImageHeight returns the value of the "og_image_height" field in the mutation.
func (m *PageInfoMutation) OgImageHeight() (r string, exists bool) {
	v := m.og_image_height
	if v == nil {
		return
	}
	return *v, true
}

// OldOgImageHeight returns the old "og_image_height" field's value of the PageInfo entity.
// If the PageInfo object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PageInfoMutation) OldOgImageHeight(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOgImageHeight is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOgImageHeight requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOgImageHeight: %w", err)
	}
	return oldValue.OgImageHeight, nil
}

// ResetOgImageHeight resets all changes to the "og_image_height" field.
func (m *PageInfoMutation) ResetOgImageHeight() {
	m.og_image_height = nil
}

// SetOgVideo sets the "og_video" field.
func (m *PageInfoMutation) SetOgVideo(s string) {
	m.og_video = &s
}

// OgVideo returns the value of the "og_video" field in the mutation.
func (m *PageInfoMutation) OgVideo() (r string, exists bool) {
	v := m.og_video
	if v == nil {
		return
	}
	return *v, true
}

// OldOgVideo returns the old "og_video" field's value of the PageInfo entity.
// If the PageInfo object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PageInfoMutation) OldOgVideo(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOgVideo is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOgVideo requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOgVideo: %w", err)
	}
	return oldValue.OgVideo, nil
}

// ResetOgVideo resets all changes to the "og_video" field.
func (m *PageInfoMutation) ResetOgVideo() {
	m.og_video = nil
}

// SetOgVideoType sets the "og_video_type" field.
func (m *PageInfoMutation) SetOgVideoType(s string) {
	m.og_video_type = &s
}

// OgVideoType returns the value of the "og_video_type" field in the mutation.
func (m *PageInfoMutation) OgVideoType() (r string, exists bool) {
	v := m.og_video_type
	if v == nil {
		return
	}
	return *v, true
}

// OldOgVideoType returns the old "og_video_type" field's value of the PageInfo entity.
// If the PageInfo object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PageInfoMutation) OldOgVideoType(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOgVideoType is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOgVideoType requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOgVideoType: %w", err)
	}
	return oldValue.OgVideoType, nil
}

// ResetOgVideoType resets all changes to the "og_video_type" field.
func (m *PageInfoMutation) ResetOgVideoType() {
	m.og_video_type = nil
}

// SetOgVideoURL sets the "og_video_url" field.
func (m *PageInfoMutation) SetOgVideoURL(s string) {
	m.og_video_url = &s
}

// OgVideoURL returns the value of the "og_video_url" field in the mutation.
func (m *PageInfoMutation) OgVideoURL() (r string, exists bool) {
	v := m.og_video_url
	if v == nil {
		return
	}
	return *v, true
}

// OldOgVideoURL returns the old "og_video_url" field's value of the PageInfo entity.
// If the PageInfo object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PageInfoMutation) OldOgVideoURL(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOgVideoURL is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOgVideoURL requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOgVideoURL: %w", err)
	}
	return oldValue.OgVideoURL, nil
}

// ResetOgVideoURL resets all changes to the "og_video_url" field.
func (m *PageInfoMutation) ResetOgVideoURL() {
	m.og_video_url = nil
}

// SetOgVideoSecureURL sets the "og_video_secure_url" field.
func (m *PageInfoMutation) SetOgVideoSecureURL(s string) {
	m.og_video_secure_url = &s
}

// OgVideoSecureURL returns the value of the "og_video_secure_url" field in the mutation.
func (m *PageInfoMutation) OgVideoSecureURL() (r string, exists bool) {
	v := m.og_video_secure_url
	if v == nil {
		return
	}
	return *v, true
}

// OldOgVideoSecureURL returns the old "og_video_secure_url" field's value of the PageInfo entity.
// If the PageInfo object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PageInfoMutation) OldOgVideoSecureURL(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOgVideoSecureURL is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOgVideoSecureURL requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOgVideoSecureURL: %w", err)
	}
	return oldValue.OgVideoSecureURL, nil
}

// ResetOgVideoSecureURL resets all changes to the "og_video_secure_url" field.
func (m *PageInfoMutation) ResetOgVideoSecureURL() {
	m.og_video_secure_url = nil
}

// SetOgVideoWidth sets the "og_video_width" field.
func (m *PageInfoMutation) SetOgVideoWidth(s string) {
	m.og_video_width = &s
}

// OgVideoWidth returns the value of the "og_video_width" field in the mutation.
func (m *PageInfoMutation) OgVideoWidth() (r string, exists bool) {
	v := m.og_video_width
	if v == nil {
		return
	}
	return *v, true
}

// OldOgVideoWidth returns the old "og_video_width" field's value of the PageInfo entity.
// If the PageInfo object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PageInfoMutation) OldOgVideoWidth(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOgVideoWidth is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOgVideoWidth requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOgVideoWidth: %w", err)
	}
	return oldValue.OgVideoWidth, nil
}

// ResetOgVideoWidth resets all changes to the "og_video_width" field.
func (m *PageInfoMutation) ResetOgVideoWidth() {
	m.og_video_width = nil
}

// SetOgVideoHeight sets the "og_video_height" field.
func (m *PageInfoMutation) SetOgVideoHeight(s string) {
	m.og_video_height = &s
}

// OgVideoHeight returns the value of the "og_video_height" field in the mutation.
func (m *PageInfoMutation) OgVideoHeight() (r string, exists bool) {
	v := m.og_video_height
	if v == nil {
		return
	}
	return *v, true
}

// OldOgVideoHeight returns the old "og_video_height" field's value of the PageInfo entity.
// If the PageInfo object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PageInfoMutation) OldOgVideoHeight(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOgVideoHeight is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOgVideoHeight requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOgVideoHeight: %w", err)
	}
	return oldValue.OgVideoHeight, nil
}

// ResetOgVideoHeight resets all changes to the "og_video_height" field.
func (m *PageInfoMutation) ResetOgVideoHeight() {
	m.og_video_height = nil
}

// Where appends a list predicates to the PageInfoMutation builder.
func (m *PageInfoMutation) Where(ps ...predicate.PageInfo) {
	m.predicates = append(m.predicates, ps...)
}

// Op returns the operation name.
func (m *PageInfoMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (PageInfo).
func (m *PageInfoMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *PageInfoMutation) Fields() []string {
	fields := make([]string, 0, 40)
	if m.domain != nil {
		fields = append(fields, pageinfo.FieldDomain)
	}
	if m.port != nil {
		fields = append(fields, pageinfo.FieldPort)
	}
	if m.is_https != nil {
		fields = append(fields, pageinfo.FieldIsHTTPS)
	}
	if m.indexed_url != nil {
		fields = append(fields, pageinfo.FieldIndexedURL)
	}
	if m._path != nil {
		fields = append(fields, pageinfo.FieldPath)
	}
	if m.querystring != nil {
		fields = append(fields, pageinfo.FieldQuerystring)
	}
	if m.url != nil {
		fields = append(fields, pageinfo.FieldURL)
	}
	if m.count_referred != nil {
		fields = append(fields, pageinfo.FieldCountReferred)
	}
	if m.status != nil {
		fields = append(fields, pageinfo.FieldStatus)
	}
	if m.created_at != nil {
		fields = append(fields, pageinfo.FieldCreatedAt)
	}
	if m.created_by != nil {
		fields = append(fields, pageinfo.FieldCreatedBy)
	}
	if m.updated_at != nil {
		fields = append(fields, pageinfo.FieldUpdatedAt)
	}
	if m.updated_by != nil {
		fields = append(fields, pageinfo.FieldUpdatedBy)
	}
	if m.title != nil {
		fields = append(fields, pageinfo.FieldTitle)
	}
	if m.description != nil {
		fields = append(fields, pageinfo.FieldDescription)
	}
	if m.keywords != nil {
		fields = append(fields, pageinfo.FieldKeywords)
	}
	if m.content_language != nil {
		fields = append(fields, pageinfo.FieldContentLanguage)
	}
	if m.twitter_card != nil {
		fields = append(fields, pageinfo.FieldTwitterCard)
	}
	if m.twitter_url != nil {
		fields = append(fields, pageinfo.FieldTwitterURL)
	}
	if m.twitter_title != nil {
		fields = append(fields, pageinfo.FieldTwitterTitle)
	}
	if m.twitter_description != nil {
		fields = append(fields, pageinfo.FieldTwitterDescription)
	}
	if m.twitter_image != nil {
		fields = append(fields, pageinfo.FieldTwitterImage)
	}
	if m.og_site_name != nil {
		fields = append(fields, pageinfo.FieldOgSiteName)
	}
	if m.og_locale != nil {
		fields = append(fields, pageinfo.FieldOgLocale)
	}
	if m.og_title != nil {
		fields = append(fields, pageinfo.FieldOgTitle)
	}
	if m.og_description != nil {
		fields = append(fields, pageinfo.FieldOgDescription)
	}
	if m.og_type != nil {
		fields = append(fields, pageinfo.FieldOgType)
	}
	if m.og_url != nil {
		fields = append(fields, pageinfo.FieldOgURL)
	}
	if m.og_image != nil {
		fields = append(fields, pageinfo.FieldOgImage)
	}
	if m.og_image_type != nil {
		fields = append(fields, pageinfo.FieldOgImageType)
	}
	if m.og_image_url != nil {
		fields = append(fields, pageinfo.FieldOgImageURL)
	}
	if m.og_image_secure_url != nil {
		fields = append(fields, pageinfo.FieldOgImageSecureURL)
	}
	if m.og_image_width != nil {
		fields = append(fields, pageinfo.FieldOgImageWidth)
	}
	if m.og_image_height != nil {
		fields = append(fields, pageinfo.FieldOgImageHeight)
	}
	if m.og_video != nil {
		fields = append(fields, pageinfo.FieldOgVideo)
	}
	if m.og_video_type != nil {
		fields = append(fields, pageinfo.FieldOgVideoType)
	}
	if m.og_video_url != nil {
		fields = append(fields, pageinfo.FieldOgVideoURL)
	}
	if m.og_video_secure_url != nil {
		fields = append(fields, pageinfo.FieldOgVideoSecureURL)
	}
	if m.og_video_width != nil {
		fields = append(fields, pageinfo.FieldOgVideoWidth)
	}
	if m.og_video_height != nil {
		fields = append(fields, pageinfo.FieldOgVideoHeight)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *PageInfoMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case pageinfo.FieldDomain:
		return m.Domain()
	case pageinfo.FieldPort:
		return m.Port()
	case pageinfo.FieldIsHTTPS:
		return m.IsHTTPS()
	case pageinfo.FieldIndexedURL:
		return m.IndexedURL()
	case pageinfo.FieldPath:
		return m.Path()
	case pageinfo.FieldQuerystring:
		return m.Querystring()
	case pageinfo.FieldURL:
		return m.URL()
	case pageinfo.FieldCountReferred:
		return m.CountReferred()
	case pageinfo.FieldStatus:
		return m.Status()
	case pageinfo.FieldCreatedAt:
		return m.CreatedAt()
	case pageinfo.FieldCreatedBy:
		return m.CreatedBy()
	case pageinfo.FieldUpdatedAt:
		return m.UpdatedAt()
	case pageinfo.FieldUpdatedBy:
		return m.UpdatedBy()
	case pageinfo.FieldTitle:
		return m.Title()
	case pageinfo.FieldDescription:
		return m.Description()
	case pageinfo.FieldKeywords:
		return m.Keywords()
	case pageinfo.FieldContentLanguage:
		return m.ContentLanguage()
	case pageinfo.FieldTwitterCard:
		return m.TwitterCard()
	case pageinfo.FieldTwitterURL:
		return m.TwitterURL()
	case pageinfo.FieldTwitterTitle:
		return m.TwitterTitle()
	case pageinfo.FieldTwitterDescription:
		return m.TwitterDescription()
	case pageinfo.FieldTwitterImage:
		return m.TwitterImage()
	case pageinfo.FieldOgSiteName:
		return m.OgSiteName()
	case pageinfo.FieldOgLocale:
		return m.OgLocale()
	case pageinfo.FieldOgTitle:
		return m.OgTitle()
	case pageinfo.FieldOgDescription:
		return m.OgDescription()
	case pageinfo.FieldOgType:
		return m.OgType()
	case pageinfo.FieldOgURL:
		return m.OgURL()
	case pageinfo.FieldOgImage:
		return m.OgImage()
	case pageinfo.FieldOgImageType:
		return m.OgImageType()
	case pageinfo.FieldOgImageURL:
		return m.OgImageURL()
	case pageinfo.FieldOgImageSecureURL:
		return m.OgImageSecureURL()
	case pageinfo.FieldOgImageWidth:
		return m.OgImageWidth()
	case pageinfo.FieldOgImageHeight:
		return m.OgImageHeight()
	case pageinfo.FieldOgVideo:
		return m.OgVideo()
	case pageinfo.FieldOgVideoType:
		return m.OgVideoType()
	case pageinfo.FieldOgVideoURL:
		return m.OgVideoURL()
	case pageinfo.FieldOgVideoSecureURL:
		return m.OgVideoSecureURL()
	case pageinfo.FieldOgVideoWidth:
		return m.OgVideoWidth()
	case pageinfo.FieldOgVideoHeight:
		return m.OgVideoHeight()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *PageInfoMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case pageinfo.FieldDomain:
		return m.OldDomain(ctx)
	case pageinfo.FieldPort:
		return m.OldPort(ctx)
	case pageinfo.FieldIsHTTPS:
		return m.OldIsHTTPS(ctx)
	case pageinfo.FieldIndexedURL:
		return m.OldIndexedURL(ctx)
	case pageinfo.FieldPath:
		return m.OldPath(ctx)
	case pageinfo.FieldQuerystring:
		return m.OldQuerystring(ctx)
	case pageinfo.FieldURL:
		return m.OldURL(ctx)
	case pageinfo.FieldCountReferred:
		return m.OldCountReferred(ctx)
	case pageinfo.FieldStatus:
		return m.OldStatus(ctx)
	case pageinfo.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case pageinfo.FieldCreatedBy:
		return m.OldCreatedBy(ctx)
	case pageinfo.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	case pageinfo.FieldUpdatedBy:
		return m.OldUpdatedBy(ctx)
	case pageinfo.FieldTitle:
		return m.OldTitle(ctx)
	case pageinfo.FieldDescription:
		return m.OldDescription(ctx)
	case pageinfo.FieldKeywords:
		return m.OldKeywords(ctx)
	case pageinfo.FieldContentLanguage:
		return m.OldContentLanguage(ctx)
	case pageinfo.FieldTwitterCard:
		return m.OldTwitterCard(ctx)
	case pageinfo.FieldTwitterURL:
		return m.OldTwitterURL(ctx)
	case pageinfo.FieldTwitterTitle:
		return m.OldTwitterTitle(ctx)
	case pageinfo.FieldTwitterDescription:
		return m.OldTwitterDescription(ctx)
	case pageinfo.FieldTwitterImage:
		return m.OldTwitterImage(ctx)
	case pageinfo.FieldOgSiteName:
		return m.OldOgSiteName(ctx)
	case pageinfo.FieldOgLocale:
		return m.OldOgLocale(ctx)
	case pageinfo.FieldOgTitle:
		return m.OldOgTitle(ctx)
	case pageinfo.FieldOgDescription:
		return m.OldOgDescription(ctx)
	case pageinfo.FieldOgType:
		return m.OldOgType(ctx)
	case pageinfo.FieldOgURL:
		return m.OldOgURL(ctx)
	case pageinfo.FieldOgImage:
		return m.OldOgImage(ctx)
	case pageinfo.FieldOgImageType:
		return m.OldOgImageType(ctx)
	case pageinfo.FieldOgImageURL:
		return m.OldOgImageURL(ctx)
	case pageinfo.FieldOgImageSecureURL:
		return m.OldOgImageSecureURL(ctx)
	case pageinfo.FieldOgImageWidth:
		return m.OldOgImageWidth(ctx)
	case pageinfo.FieldOgImageHeight:
		return m.OldOgImageHeight(ctx)
	case pageinfo.FieldOgVideo:
		return m.OldOgVideo(ctx)
	case pageinfo.FieldOgVideoType:
		return m.OldOgVideoType(ctx)
	case pageinfo.FieldOgVideoURL:
		return m.OldOgVideoURL(ctx)
	case pageinfo.FieldOgVideoSecureURL:
		return m.OldOgVideoSecureURL(ctx)
	case pageinfo.FieldOgVideoWidth:
		return m.OldOgVideoWidth(ctx)
	case pageinfo.FieldOgVideoHeight:
		return m.OldOgVideoHeight(ctx)
	}
	return nil, fmt.Errorf("unknown PageInfo field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *PageInfoMutation) SetField(name string, value ent.Value) error {
	switch name {
	case pageinfo.FieldDomain:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDomain(v)
		return nil
	case pageinfo.FieldPort:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPort(v)
		return nil
	case pageinfo.FieldIsHTTPS:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIsHTTPS(v)
		return nil
	case pageinfo.FieldIndexedURL:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIndexedURL(v)
		return nil
	case pageinfo.FieldPath:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPath(v)
		return nil
	case pageinfo.FieldQuerystring:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetQuerystring(v)
		return nil
	case pageinfo.FieldURL:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetURL(v)
		return nil
	case pageinfo.FieldCountReferred:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCountReferred(v)
		return nil
	case pageinfo.FieldStatus:
		v, ok := value.(pageinfo.Status)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatus(v)
		return nil
	case pageinfo.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case pageinfo.FieldCreatedBy:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedBy(v)
		return nil
	case pageinfo.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	case pageinfo.FieldUpdatedBy:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedBy(v)
		return nil
	case pageinfo.FieldTitle:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTitle(v)
		return nil
	case pageinfo.FieldDescription:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDescription(v)
		return nil
	case pageinfo.FieldKeywords:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetKeywords(v)
		return nil
	case pageinfo.FieldContentLanguage:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetContentLanguage(v)
		return nil
	case pageinfo.FieldTwitterCard:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTwitterCard(v)
		return nil
	case pageinfo.FieldTwitterURL:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTwitterURL(v)
		return nil
	case pageinfo.FieldTwitterTitle:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTwitterTitle(v)
		return nil
	case pageinfo.FieldTwitterDescription:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTwitterDescription(v)
		return nil
	case pageinfo.FieldTwitterImage:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTwitterImage(v)
		return nil
	case pageinfo.FieldOgSiteName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOgSiteName(v)
		return nil
	case pageinfo.FieldOgLocale:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOgLocale(v)
		return nil
	case pageinfo.FieldOgTitle:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOgTitle(v)
		return nil
	case pageinfo.FieldOgDescription:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOgDescription(v)
		return nil
	case pageinfo.FieldOgType:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOgType(v)
		return nil
	case pageinfo.FieldOgURL:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOgURL(v)
		return nil
	case pageinfo.FieldOgImage:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOgImage(v)
		return nil
	case pageinfo.FieldOgImageType:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOgImageType(v)
		return nil
	case pageinfo.FieldOgImageURL:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOgImageURL(v)
		return nil
	case pageinfo.FieldOgImageSecureURL:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOgImageSecureURL(v)
		return nil
	case pageinfo.FieldOgImageWidth:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOgImageWidth(v)
		return nil
	case pageinfo.FieldOgImageHeight:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOgImageHeight(v)
		return nil
	case pageinfo.FieldOgVideo:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOgVideo(v)
		return nil
	case pageinfo.FieldOgVideoType:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOgVideoType(v)
		return nil
	case pageinfo.FieldOgVideoURL:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOgVideoURL(v)
		return nil
	case pageinfo.FieldOgVideoSecureURL:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOgVideoSecureURL(v)
		return nil
	case pageinfo.FieldOgVideoWidth:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOgVideoWidth(v)
		return nil
	case pageinfo.FieldOgVideoHeight:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOgVideoHeight(v)
		return nil
	}
	return fmt.Errorf("unknown PageInfo field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *PageInfoMutation) AddedFields() []string {
	var fields []string
	if m.addcount_referred != nil {
		fields = append(fields, pageinfo.FieldCountReferred)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *PageInfoMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case pageinfo.FieldCountReferred:
		return m.AddedCountReferred()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *PageInfoMutation) AddField(name string, value ent.Value) error {
	switch name {
	case pageinfo.FieldCountReferred:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddCountReferred(v)
		return nil
	}
	return fmt.Errorf("unknown PageInfo numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *PageInfoMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *PageInfoMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *PageInfoMutation) ClearField(name string) error {
	return fmt.Errorf("unknown PageInfo nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *PageInfoMutation) ResetField(name string) error {
	switch name {
	case pageinfo.FieldDomain:
		m.ResetDomain()
		return nil
	case pageinfo.FieldPort:
		m.ResetPort()
		return nil
	case pageinfo.FieldIsHTTPS:
		m.ResetIsHTTPS()
		return nil
	case pageinfo.FieldIndexedURL:
		m.ResetIndexedURL()
		return nil
	case pageinfo.FieldPath:
		m.ResetPath()
		return nil
	case pageinfo.FieldQuerystring:
		m.ResetQuerystring()
		return nil
	case pageinfo.FieldURL:
		m.ResetURL()
		return nil
	case pageinfo.FieldCountReferred:
		m.ResetCountReferred()
		return nil
	case pageinfo.FieldStatus:
		m.ResetStatus()
		return nil
	case pageinfo.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case pageinfo.FieldCreatedBy:
		m.ResetCreatedBy()
		return nil
	case pageinfo.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	case pageinfo.FieldUpdatedBy:
		m.ResetUpdatedBy()
		return nil
	case pageinfo.FieldTitle:
		m.ResetTitle()
		return nil
	case pageinfo.FieldDescription:
		m.ResetDescription()
		return nil
	case pageinfo.FieldKeywords:
		m.ResetKeywords()
		return nil
	case pageinfo.FieldContentLanguage:
		m.ResetContentLanguage()
		return nil
	case pageinfo.FieldTwitterCard:
		m.ResetTwitterCard()
		return nil
	case pageinfo.FieldTwitterURL:
		m.ResetTwitterURL()
		return nil
	case pageinfo.FieldTwitterTitle:
		m.ResetTwitterTitle()
		return nil
	case pageinfo.FieldTwitterDescription:
		m.ResetTwitterDescription()
		return nil
	case pageinfo.FieldTwitterImage:
		m.ResetTwitterImage()
		return nil
	case pageinfo.FieldOgSiteName:
		m.ResetOgSiteName()
		return nil
	case pageinfo.FieldOgLocale:
		m.ResetOgLocale()
		return nil
	case pageinfo.FieldOgTitle:
		m.ResetOgTitle()
		return nil
	case pageinfo.FieldOgDescription:
		m.ResetOgDescription()
		return nil
	case pageinfo.FieldOgType:
		m.ResetOgType()
		return nil
	case pageinfo.FieldOgURL:
		m.ResetOgURL()
		return nil
	case pageinfo.FieldOgImage:
		m.ResetOgImage()
		return nil
	case pageinfo.FieldOgImageType:
		m.ResetOgImageType()
		return nil
	case pageinfo.FieldOgImageURL:
		m.ResetOgImageURL()
		return nil
	case pageinfo.FieldOgImageSecureURL:
		m.ResetOgImageSecureURL()
		return nil
	case pageinfo.FieldOgImageWidth:
		m.ResetOgImageWidth()
		return nil
	case pageinfo.FieldOgImageHeight:
		m.ResetOgImageHeight()
		return nil
	case pageinfo.FieldOgVideo:
		m.ResetOgVideo()
		return nil
	case pageinfo.FieldOgVideoType:
		m.ResetOgVideoType()
		return nil
	case pageinfo.FieldOgVideoURL:
		m.ResetOgVideoURL()
		return nil
	case pageinfo.FieldOgVideoSecureURL:
		m.ResetOgVideoSecureURL()
		return nil
	case pageinfo.FieldOgVideoWidth:
		m.ResetOgVideoWidth()
		return nil
	case pageinfo.FieldOgVideoHeight:
		m.ResetOgVideoHeight()
		return nil
	}
	return fmt.Errorf("unknown PageInfo field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *PageInfoMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *PageInfoMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *PageInfoMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *PageInfoMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *PageInfoMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *PageInfoMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *PageInfoMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown PageInfo unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *PageInfoMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown PageInfo edge %s", name)
}

// PageLinkMutation represents an operation that mutates the PageLink nodes in the graph.
type PageLinkMutation struct {
	config
	op            Op
	typ           string
	id            *int64
	source_id     *int64
	addsource_id  *int64
	target_id     *int64
	addtarget_id  *int64
	created_at    *time.Time
	created_by    *string
	updated_at    *time.Time
	updated_by    *string
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*PageLink, error)
	predicates    []predicate.PageLink
}

var _ ent.Mutation = (*PageLinkMutation)(nil)

// pagelinkOption allows management of the mutation configuration using functional options.
type pagelinkOption func(*PageLinkMutation)

// newPageLinkMutation creates new mutation for the PageLink entity.
func newPageLinkMutation(c config, op Op, opts ...pagelinkOption) *PageLinkMutation {
	m := &PageLinkMutation{
		config:        c,
		op:            op,
		typ:           TypePageLink,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withPageLinkID sets the ID field of the mutation.
func withPageLinkID(id int64) pagelinkOption {
	return func(m *PageLinkMutation) {
		var (
			err   error
			once  sync.Once
			value *PageLink
		)
		m.oldValue = func(ctx context.Context) (*PageLink, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().PageLink.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withPageLink sets the old PageLink of the mutation.
func withPageLink(node *PageLink) pagelinkOption {
	return func(m *PageLinkMutation) {
		m.oldValue = func(context.Context) (*PageLink, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m PageLinkMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m PageLinkMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of PageLink entities.
func (m *PageLinkMutation) SetID(id int64) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *PageLinkMutation) ID() (id int64, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *PageLinkMutation) IDs(ctx context.Context) ([]int64, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int64{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().PageLink.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetSourceID sets the "source_id" field.
func (m *PageLinkMutation) SetSourceID(i int64) {
	m.source_id = &i
	m.addsource_id = nil
}

// SourceID returns the value of the "source_id" field in the mutation.
func (m *PageLinkMutation) SourceID() (r int64, exists bool) {
	v := m.source_id
	if v == nil {
		return
	}
	return *v, true
}

// OldSourceID returns the old "source_id" field's value of the PageLink entity.
// If the PageLink object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PageLinkMutation) OldSourceID(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSourceID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSourceID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSourceID: %w", err)
	}
	return oldValue.SourceID, nil
}

// AddSourceID adds i to the "source_id" field.
func (m *PageLinkMutation) AddSourceID(i int64) {
	if m.addsource_id != nil {
		*m.addsource_id += i
	} else {
		m.addsource_id = &i
	}
}

// AddedSourceID returns the value that was added to the "source_id" field in this mutation.
func (m *PageLinkMutation) AddedSourceID() (r int64, exists bool) {
	v := m.addsource_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetSourceID resets all changes to the "source_id" field.
func (m *PageLinkMutation) ResetSourceID() {
	m.source_id = nil
	m.addsource_id = nil
}

// SetTargetID sets the "target_id" field.
func (m *PageLinkMutation) SetTargetID(i int64) {
	m.target_id = &i
	m.addtarget_id = nil
}

// TargetID returns the value of the "target_id" field in the mutation.
func (m *PageLinkMutation) TargetID() (r int64, exists bool) {
	v := m.target_id
	if v == nil {
		return
	}
	return *v, true
}

// OldTargetID returns the old "target_id" field's value of the PageLink entity.
// If the PageLink object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PageLinkMutation) OldTargetID(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTargetID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTargetID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTargetID: %w", err)
	}
	return oldValue.TargetID, nil
}

// AddTargetID adds i to the "target_id" field.
func (m *PageLinkMutation) AddTargetID(i int64) {
	if m.addtarget_id != nil {
		*m.addtarget_id += i
	} else {
		m.addtarget_id = &i
	}
}

// AddedTargetID returns the value that was added to the "target_id" field in this mutation.
func (m *PageLinkMutation) AddedTargetID() (r int64, exists bool) {
	v := m.addtarget_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetTargetID resets all changes to the "target_id" field.
func (m *PageLinkMutation) ResetTargetID() {
	m.target_id = nil
	m.addtarget_id = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *PageLinkMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *PageLinkMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the PageLink entity.
// If the PageLink object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PageLinkMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *PageLinkMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetCreatedBy sets the "created_by" field.
func (m *PageLinkMutation) SetCreatedBy(s string) {
	m.created_by = &s
}

// CreatedBy returns the value of the "created_by" field in the mutation.
func (m *PageLinkMutation) CreatedBy() (r string, exists bool) {
	v := m.created_by
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedBy returns the old "created_by" field's value of the PageLink entity.
// If the PageLink object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PageLinkMutation) OldCreatedBy(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedBy is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedBy requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedBy: %w", err)
	}
	return oldValue.CreatedBy, nil
}

// ResetCreatedBy resets all changes to the "created_by" field.
func (m *PageLinkMutation) ResetCreatedBy() {
	m.created_by = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *PageLinkMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *PageLinkMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the PageLink entity.
// If the PageLink object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PageLinkMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *PageLinkMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// SetUpdatedBy sets the "updated_by" field.
func (m *PageLinkMutation) SetUpdatedBy(s string) {
	m.updated_by = &s
}

// UpdatedBy returns the value of the "updated_by" field in the mutation.
func (m *PageLinkMutation) UpdatedBy() (r string, exists bool) {
	v := m.updated_by
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedBy returns the old "updated_by" field's value of the PageLink entity.
// If the PageLink object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PageLinkMutation) OldUpdatedBy(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedBy is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedBy requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedBy: %w", err)
	}
	return oldValue.UpdatedBy, nil
}

// ResetUpdatedBy resets all changes to the "updated_by" field.
func (m *PageLinkMutation) ResetUpdatedBy() {
	m.updated_by = nil
}

// Where appends a list predicates to the PageLinkMutation builder.
func (m *PageLinkMutation) Where(ps ...predicate.PageLink) {
	m.predicates = append(m.predicates, ps...)
}

// Op returns the operation name.
func (m *PageLinkMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (PageLink).
func (m *PageLinkMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *PageLinkMutation) Fields() []string {
	fields := make([]string, 0, 6)
	if m.source_id != nil {
		fields = append(fields, pagelink.FieldSourceID)
	}
	if m.target_id != nil {
		fields = append(fields, pagelink.FieldTargetID)
	}
	if m.created_at != nil {
		fields = append(fields, pagelink.FieldCreatedAt)
	}
	if m.created_by != nil {
		fields = append(fields, pagelink.FieldCreatedBy)
	}
	if m.updated_at != nil {
		fields = append(fields, pagelink.FieldUpdatedAt)
	}
	if m.updated_by != nil {
		fields = append(fields, pagelink.FieldUpdatedBy)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *PageLinkMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case pagelink.FieldSourceID:
		return m.SourceID()
	case pagelink.FieldTargetID:
		return m.TargetID()
	case pagelink.FieldCreatedAt:
		return m.CreatedAt()
	case pagelink.FieldCreatedBy:
		return m.CreatedBy()
	case pagelink.FieldUpdatedAt:
		return m.UpdatedAt()
	case pagelink.FieldUpdatedBy:
		return m.UpdatedBy()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *PageLinkMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case pagelink.FieldSourceID:
		return m.OldSourceID(ctx)
	case pagelink.FieldTargetID:
		return m.OldTargetID(ctx)
	case pagelink.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case pagelink.FieldCreatedBy:
		return m.OldCreatedBy(ctx)
	case pagelink.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	case pagelink.FieldUpdatedBy:
		return m.OldUpdatedBy(ctx)
	}
	return nil, fmt.Errorf("unknown PageLink field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *PageLinkMutation) SetField(name string, value ent.Value) error {
	switch name {
	case pagelink.FieldSourceID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSourceID(v)
		return nil
	case pagelink.FieldTargetID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTargetID(v)
		return nil
	case pagelink.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case pagelink.FieldCreatedBy:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedBy(v)
		return nil
	case pagelink.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	case pagelink.FieldUpdatedBy:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedBy(v)
		return nil
	}
	return fmt.Errorf("unknown PageLink field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *PageLinkMutation) AddedFields() []string {
	var fields []string
	if m.addsource_id != nil {
		fields = append(fields, pagelink.FieldSourceID)
	}
	if m.addtarget_id != nil {
		fields = append(fields, pagelink.FieldTargetID)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *PageLinkMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case pagelink.FieldSourceID:
		return m.AddedSourceID()
	case pagelink.FieldTargetID:
		return m.AddedTargetID()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *PageLinkMutation) AddField(name string, value ent.Value) error {
	switch name {
	case pagelink.FieldSourceID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddSourceID(v)
		return nil
	case pagelink.FieldTargetID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddTargetID(v)
		return nil
	}
	return fmt.Errorf("unknown PageLink numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *PageLinkMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *PageLinkMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *PageLinkMutation) ClearField(name string) error {
	return fmt.Errorf("unknown PageLink nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *PageLinkMutation) ResetField(name string) error {
	switch name {
	case pagelink.FieldSourceID:
		m.ResetSourceID()
		return nil
	case pagelink.FieldTargetID:
		m.ResetTargetID()
		return nil
	case pagelink.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case pagelink.FieldCreatedBy:
		m.ResetCreatedBy()
		return nil
	case pagelink.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	case pagelink.FieldUpdatedBy:
		m.ResetUpdatedBy()
		return nil
	}
	return fmt.Errorf("unknown PageLink field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *PageLinkMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *PageLinkMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *PageLinkMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *PageLinkMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *PageLinkMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *PageLinkMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *PageLinkMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown PageLink unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *PageLinkMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown PageLink edge %s", name)
}
