// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/drakejin/crawler/internal/storage/db/ent/pagereferred"
	"github.com/drakejin/crawler/internal/storage/db/ent/predicate"
	"github.com/google/uuid"
)

// PageReferredQuery is the builder for querying PageReferred entities.
type PageReferredQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.PageReferred
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PageReferredQuery builder.
func (prq *PageReferredQuery) Where(ps ...predicate.PageReferred) *PageReferredQuery {
	prq.predicates = append(prq.predicates, ps...)
	return prq
}

// Limit adds a limit step to the query.
func (prq *PageReferredQuery) Limit(limit int) *PageReferredQuery {
	prq.limit = &limit
	return prq
}

// Offset adds an offset step to the query.
func (prq *PageReferredQuery) Offset(offset int) *PageReferredQuery {
	prq.offset = &offset
	return prq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (prq *PageReferredQuery) Unique(unique bool) *PageReferredQuery {
	prq.unique = &unique
	return prq
}

// Order adds an order step to the query.
func (prq *PageReferredQuery) Order(o ...OrderFunc) *PageReferredQuery {
	prq.order = append(prq.order, o...)
	return prq
}

// First returns the first PageReferred entity from the query.
// Returns a *NotFoundError when no PageReferred was found.
func (prq *PageReferredQuery) First(ctx context.Context) (*PageReferred, error) {
	nodes, err := prq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{pagereferred.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (prq *PageReferredQuery) FirstX(ctx context.Context) *PageReferred {
	node, err := prq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PageReferred ID from the query.
// Returns a *NotFoundError when no PageReferred ID was found.
func (prq *PageReferredQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = prq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{pagereferred.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (prq *PageReferredQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := prq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PageReferred entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PageReferred entity is found.
// Returns a *NotFoundError when no PageReferred entities are found.
func (prq *PageReferredQuery) Only(ctx context.Context) (*PageReferred, error) {
	nodes, err := prq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{pagereferred.Label}
	default:
		return nil, &NotSingularError{pagereferred.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (prq *PageReferredQuery) OnlyX(ctx context.Context) *PageReferred {
	node, err := prq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PageReferred ID in the query.
// Returns a *NotSingularError when more than one PageReferred ID is found.
// Returns a *NotFoundError when no entities are found.
func (prq *PageReferredQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = prq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{pagereferred.Label}
	default:
		err = &NotSingularError{pagereferred.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (prq *PageReferredQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := prq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PageReferreds.
func (prq *PageReferredQuery) All(ctx context.Context) ([]*PageReferred, error) {
	if err := prq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return prq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (prq *PageReferredQuery) AllX(ctx context.Context) []*PageReferred {
	nodes, err := prq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PageReferred IDs.
func (prq *PageReferredQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := prq.Select(pagereferred.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (prq *PageReferredQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := prq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (prq *PageReferredQuery) Count(ctx context.Context) (int, error) {
	if err := prq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return prq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (prq *PageReferredQuery) CountX(ctx context.Context) int {
	count, err := prq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (prq *PageReferredQuery) Exist(ctx context.Context) (bool, error) {
	if err := prq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return prq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (prq *PageReferredQuery) ExistX(ctx context.Context) bool {
	exist, err := prq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PageReferredQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (prq *PageReferredQuery) Clone() *PageReferredQuery {
	if prq == nil {
		return nil
	}
	return &PageReferredQuery{
		config:     prq.config,
		limit:      prq.limit,
		offset:     prq.offset,
		order:      append([]OrderFunc{}, prq.order...),
		predicates: append([]predicate.PageReferred{}, prq.predicates...),
		// clone intermediate query.
		sql:    prq.sql.Clone(),
		path:   prq.path,
		unique: prq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		SourceID uuid.UUID `json:"source_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PageReferred.Query().
//		GroupBy(pagereferred.FieldSourceID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (prq *PageReferredQuery) GroupBy(field string, fields ...string) *PageReferredGroupBy {
	grbuild := &PageReferredGroupBy{config: prq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := prq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return prq.sqlQuery(ctx), nil
	}
	grbuild.label = pagereferred.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		SourceID uuid.UUID `json:"source_id,omitempty"`
//	}
//
//	client.PageReferred.Query().
//		Select(pagereferred.FieldSourceID).
//		Scan(ctx, &v)
func (prq *PageReferredQuery) Select(fields ...string) *PageReferredSelect {
	prq.fields = append(prq.fields, fields...)
	selbuild := &PageReferredSelect{PageReferredQuery: prq}
	selbuild.label = pagereferred.Label
	selbuild.flds, selbuild.scan = &prq.fields, selbuild.Scan
	return selbuild
}

// Aggregate returns a PageReferredSelect configured with the given aggregations.
func (prq *PageReferredQuery) Aggregate(fns ...AggregateFunc) *PageReferredSelect {
	return prq.Select().Aggregate(fns...)
}

func (prq *PageReferredQuery) prepareQuery(ctx context.Context) error {
	for _, f := range prq.fields {
		if !pagereferred.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if prq.path != nil {
		prev, err := prq.path(ctx)
		if err != nil {
			return err
		}
		prq.sql = prev
	}
	return nil
}

func (prq *PageReferredQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PageReferred, error) {
	var (
		nodes = []*PageReferred{}
		_spec = prq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PageReferred).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PageReferred{config: prq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, prq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (prq *PageReferredQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := prq.querySpec()
	_spec.Node.Columns = prq.fields
	if len(prq.fields) > 0 {
		_spec.Unique = prq.unique != nil && *prq.unique
	}
	return sqlgraph.CountNodes(ctx, prq.driver, _spec)
}

func (prq *PageReferredQuery) sqlExist(ctx context.Context) (bool, error) {
	switch _, err := prq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

func (prq *PageReferredQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   pagereferred.Table,
			Columns: pagereferred.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: pagereferred.FieldID,
			},
		},
		From:   prq.sql,
		Unique: true,
	}
	if unique := prq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := prq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pagereferred.FieldID)
		for i := range fields {
			if fields[i] != pagereferred.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := prq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := prq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := prq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := prq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (prq *PageReferredQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(prq.driver.Dialect())
	t1 := builder.Table(pagereferred.Table)
	columns := prq.fields
	if len(columns) == 0 {
		columns = pagereferred.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if prq.sql != nil {
		selector = prq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if prq.unique != nil && *prq.unique {
		selector.Distinct()
	}
	for _, p := range prq.predicates {
		p(selector)
	}
	for _, p := range prq.order {
		p(selector)
	}
	if offset := prq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := prq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PageReferredGroupBy is the group-by builder for PageReferred entities.
type PageReferredGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (prgb *PageReferredGroupBy) Aggregate(fns ...AggregateFunc) *PageReferredGroupBy {
	prgb.fns = append(prgb.fns, fns...)
	return prgb
}

// Scan applies the group-by query and scans the result into the given value.
func (prgb *PageReferredGroupBy) Scan(ctx context.Context, v any) error {
	query, err := prgb.path(ctx)
	if err != nil {
		return err
	}
	prgb.sql = query
	return prgb.sqlScan(ctx, v)
}

func (prgb *PageReferredGroupBy) sqlScan(ctx context.Context, v any) error {
	for _, f := range prgb.fields {
		if !pagereferred.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := prgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := prgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (prgb *PageReferredGroupBy) sqlQuery() *sql.Selector {
	selector := prgb.sql.Select()
	aggregation := make([]string, 0, len(prgb.fns))
	for _, fn := range prgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(prgb.fields)+len(prgb.fns))
		for _, f := range prgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(prgb.fields...)...)
}

// PageReferredSelect is the builder for selecting fields of PageReferred entities.
type PageReferredSelect struct {
	*PageReferredQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (prs *PageReferredSelect) Aggregate(fns ...AggregateFunc) *PageReferredSelect {
	prs.fns = append(prs.fns, fns...)
	return prs
}

// Scan applies the selector query and scans the result into the given value.
func (prs *PageReferredSelect) Scan(ctx context.Context, v any) error {
	if err := prs.prepareQuery(ctx); err != nil {
		return err
	}
	prs.sql = prs.PageReferredQuery.sqlQuery(ctx)
	return prs.sqlScan(ctx, v)
}

func (prs *PageReferredSelect) sqlScan(ctx context.Context, v any) error {
	aggregation := make([]string, 0, len(prs.fns))
	for _, fn := range prs.fns {
		aggregation = append(aggregation, fn(prs.sql))
	}
	switch n := len(*prs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		prs.sql.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		prs.sql.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := prs.sql.Query()
	if err := prs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
