services:
  crawler_db:
    platform: linux/x86_64
    image: mysql:8.0.28
    container_name: crawler_db
    ports:
      - "23306:3306"
    environment:
      - MYSQL_DATABASE=indexer
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=passwd
      - MYSQL_ROOT_PASSWORD=passwd
