// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Page is the predicate function for page builders.
type Page func(*sql.Selector)

// PageReferred is the predicate function for pagereferred builders.
type PageReferred func(*sql.Selector)

// PageSource is the predicate function for pagesource builders.
type PageSource func(*sql.Selector)
